### ISSUE TITLE
How to clean logs and database for disk cleaning and SSL ?

### ISSUE THREAD

**Issue by eix128** [linagora/james-project#3396]
1-)
Hi , i have installed james , but how can i clean logs and database from docker ? 
I want to clean everything including mails after i got mails. 

2-)
BTW , I am using thunderbird.
How can i enable and USE SSL Enabled James ? Now passwords sending unencrypted and my network everybody can listen network and got my password and e-mail datas.
I dont know how to configure Thunderbird and docker to enable SSL Password auth and encrypted mails.

3-) Sometimes on thunderbird i got error on thunderbird.
It says fetch processing failed.
Why this happens ? is there any error ? How can i see errors?

4-) Some people trying bruteforcing my server.For auth

00:36:47.240 [ERROR] o.a.j.p.a.h.CommandHandler - AUTH method LOGIN failed from Username{localPart=rapid, domainPart=Optional[Domain : xxxx.com]}@45.142.195.15

is there any config to block ip after many auth attempts ?

**Comment by chibenwa** [comment]
Hello,

I will try to answer your questions.

4) This feature is currently not built in James but it should be easy to leverage it using the `fail2ban` utility.

3) Do you see some errors on James side? If you can provide us the stacktraces, it could help. 

2) For sure! Use port 993 instead of 143. Be aware that self signed certificates might demand some thunderbird tricks to be accepted. Same thing for SMTP.

1) I don't understand your question.

Regards,

Benoit

**Comment by eix128** [comment]
I just changed the port but failed.Could not connect to SMTP server.
What to do ? Passwords also going over network as plain text :(
How to solve issue thunderbird ?


Re: or sure! Use port 993 instead of 143. Be aware that self signed certificates might demand some thunderbird tricks to be accepted. Same thing for SMTP.

**Comment by chibenwa** [comment]
Hi @eix128 

When using port 993 you have to configure tbird to use ssl.

Dont hesitate to attach screenshot for additional guidance.

Cheers

Benoit
