### ISSUE TITLE
Bug > Able to create a mailbox with the name contains '&'

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3803]
# Actual Result

It is able to create or update mailbox name contains `&` character, which is not displaying correctly on OpenPaas 

![image](https://user-images.githubusercontent.com/69950655/93861497-cec84680-fcea-11ea-907f-85a601b78d55.png)
![image](https://user-images.githubusercontent.com/69950655/93861535-dd166280-fcea-11ea-97b0-3468beb72816.png)

# Expected Result
It shouldn't allow `&` character in the mailbox name.
Please also update the error message, example:
"description": "#private:userd@qa.open-paas.org:mailbox#mailbox contains one of the forbidden characters %*#"

**Comment by chibenwa** [comment]
@tlle14 see https://github.com/linagora/james-project/issues/3759

We now allow the creation of mailboxes with `&` in their name:

 - Because people often use `&` and this creates many issue upon imapsync
 - Because UTF-7 enable to escape it at the IMAP level.

If you encouter some places (webadmin documentation?) that is not up to date, then don't hesitate to open bug reports with the documentation label ;-)

Cheers,

**Comment by tlle14** [comment]
Thank @chibenwa 

So I should close this ticket for it's not an issue

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/3805 updates webadmin documentation accordingly.
