### ISSUE TITLE
Bug > Thunderbird > The order of mailboxes on Thunderbird is incorrect

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3960]
# Actual Result

On Thunderbird, the order of Outbox and Spam - which are the default mailboxes is incorrect.
![image](https://user-images.githubusercontent.com/69950655/97255195-ad56ff00-1842-11eb-8301-c65380965083.png)

# Expected result
The mailboxes should be sorted by sortOrder.

**Comment by chibenwa** [comment]
> The mailboxes should be sorted by sortOrder.

That is incorrect.

SortOrder is a JMAP specific concept.

Here the issue is that `Spam` and `Outbox` are not recognised as special role mailboxes.

The solution would be to implement https://tools.ietf.org/html/rfc6154 in order to cary other Special Use in IMAP.

`Spam` mailbox should receive the `\Junk` Special use.

However `Outbox` is more problematic... https://www.iana.org/assignments/imap-mailbox-name-attributes/imap-mailbox-name-attributes.xhtml do not have any special `Outbox`.

The long term solution would be to kill the Outbox role on James server side. We would create sent mails directly in the sent mailbox and rely on EmailSubmission/query to display a (virtual) outbox on Inbox frontend. But we are very far from this.

**Comment by MichaelBailly** [comment]
Is `Outbox` of any use on IMAP ? Or should James just not send it when the protocol is Imap ?

**Comment by chibenwa** [comment]
@MichaelBailly regarding the latest JMAP spec it would be an implementation detail of INBOX.

> Is Outbox of any use on IMAP ?

No

> should James just not send it when the protocol is Imap ?

Could be a solution to filter it out, yes.

**Comment by chibenwa** [comment]
https://www.rfc-editor.org/rfc/rfc6154 -> ???

**Comment by chibenwa** [comment]
I opened issues for this: https://github.com/linagora/james-project/issues/4677

Needs https://github.com/linagora/james-project/issues/4675
