### ISSUE TITLE
Please,how to route to multiple james sites

### ISSUE THREAD

**Issue by panglei1984** [linagora/james-project#4175]
If  I have two James servers deployed in different regions, assuming they are James_A server in region A and James_B server in region B. 
There are different users A@james.com In James_A server and B@james.com In James_ B server.

The question is: Now I use gmail account test@gmail.com to send email to user A@james.com. How to correctly route to James_A.

**Comment by chibenwa** [comment]
Hi!

You could think of another Mail Exchange server knowing were to route the mail. I think tooling to split email traffic within a single doimain is currently missing from the project.

Or, if serverA receives an email:
 - Using RecipientIsLocal, he knows if the email is for one of his users
 - otherwize if the mail for james.com is not for us we forward it to server B
 
 Server B does the same...
 
 I advise being careful avoiding loops between serverA & serverB: you can set a header saying the email had been relayed already.
 
 Be sure ti dis-activate "ValidRcptHandler" (otherwize serverA & B would reject users of james.com they don't known but could potentially belong to the other server)...

Would it solve your issue?

Cheers,

Benoit

**Comment by panglei1984** [comment]
> Or, if serverA receives an email:
> 
> * Using RecipientIsLocal, he knows if the email is for one of his users
> * otherwize if the mail for james.com is not for us we forward it to server B
> 
> Server B does the same...

Do you know whether the smtp protocol supports this.It means james return protocol error,then the 3rd smtp server will router to server B. 
Or I need  add the feature in james to be a reverse proxy for transparent transmission to server B

**Comment by chibenwa** [comment]
> Or I need add the feature in james to be a reverse proxy for transparent transmission to server B

That likely would be the cleanest way.

I bet that configurable whitelist mailet would be the cleanest way to do this (eg: https://github.com/chibenwa/james-blacklist ). You could create an address list to be routed to server A, an address list to be routed to serverB, and reject everything not in these two lists. The project mentionned above could be used to demonstrate how to build custom matchers, with persistence, and with a webadmin route exposed to govern it (given that you uses Guice packagings of the Apache James server).

We can offer consulting to set up such a solution, based on your needs ;-) Otherwise we can of course continue providing you "community" support ;-)

> Do you know whether the smtp protocol supports this.It means james return protocol error,then the 3rd smtp server will router to server B.

Supports what? Bounces are sent to the Return-Path header value of the sent message. DSN extension allow error monitoring of a complex sending chain. We should be good...

**Comment by panglei1984** [comment]
> Supports what? Bounces are sent to the Return-Path header value of the sent message. DSN extension allow error monitoring of a complex sending chain. We should be good...

For example, in Gmail client，test@gmail.com send email to A@james.com .The smtp message is first routed to James B server. 
Is it possible for James B server to return information and tell Gmail client to resend the smtp message to James A server, instead of james B server sending it to James A server ? Because i don't want data of the message(in smtp data command) to go through james B server.

**Comment by chibenwa** [comment]
> Is it possible for James B server to return information and tell Gmail client to resend the smtp message to James A server, instead of james B server sending it to James A server ? 

No it is not.

serverA should route that email to serverB.

> Because i don't want data of the message(in smtp data command) to go through james B server.

Then you need some kind of proxy on front of your sharded mail infrastucture...

**Comment by panglei1984** [comment]
@chibenwa 
Can mail relay of James achieve this goal？

**Comment by chibenwa** [comment]
Given some extra development, yes, very likely.
