### ISSUE TITLE
[JIB] Avoid using root as a user

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4618]
https://issues.apache.org/jira/browse/JAMES-3818

JIB by default uses root as a user for the app within the container, which can raise security question, and is against best practices.

To quote https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

```
If a service can run without privileges, use USER to change to a non-root user. Start by creating the user and group in the Dockerfile with something like:

RUN groupadd -r postgres && useradd --no-log-init -r -g postgres postgres
```

With JIB it is fairly easy to use the `nobody` user though I did stop my investigations on permission management (for files add).

It might require us to switch things out of the root folder. The JIB community do not seem to actively go in that direction too...

I'm not actively working in this but if somebody wants to get a try...

**Comment by Arsnael** [comment]
I gave a try on TMail memory here: https://github.com/linagora/tmail-backend/pull/476 (I know it's a apache james issue but was easier to experiment this)

A bit of a pain IMO, JIB is not really thought for that obviously. They seem to want to push mainly the responsibility to the base docker image that should create that non root user, assign it to a group and assign his working directory to it.

This it TMail memory with a `nobody` user... It runs... but I had to:

- change most ports (non root user can't use privileged ports like 25, 143, 80, ...)
- mount a bs empty file for logs and then put a 777 permission on it (because all the folders and files still belong to root user... so no choice if you want to write. Note that it is an issue for log rotation saves though)
- as said above no folder belongs to that nobody user...

I think the cleanest way to do it is to create our own Dockerfile image creating a james user with its group, creating a working directory that james would be owner of and have all his related files mounted there.

But that means having to maintain our own images though... And regarding Apache James I'm not exactly sure the way to proceed either regarding this option.

@chibenwa thoughts?

**Comment by chibenwa** [comment]
As said on the PR I am buying the POC

Let's adopt this onto TMail.

Let's propose it onto James community with upgrade instructions.

**Comment by Arsnael** [comment]
Or not... as said in the PR:

Glowroot:
```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/home/nobody/glowroot/glowroot.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended 
Glowroot failed to start: Could not create directory: /home/nobody/glowroot/tmp
java.io.IOException: Could not create directory: /home/nobody/glowroot/tmp
        at org.glowroot.agent.NotGuava.mkdirs(NotGuava.java:31)
        at org.glowroot.agent.Directories.<init>(Directories.java:119)
        at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:104)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)                                                                   
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
```

CLI:
```
docker exec -it james james-cli ListDomains
Error: Could not find or load main class org.apache.james.cli.ServerCmd
Caused by: java.lang.ClassNotFoundException: org.apache.james.cli.ServerCmd
```

Profiler:
```
nobody@7ef68e76e9cd:/home/nobody/async-profiler$ ./profiler.sh 1 
[WARN] Kernel symbols are unavailable due to restrictions. Try   
  sysctl kernel.kptr_restrict=0                                                            
  sysctl kernel.perf_event_paranoid=1                                                      
[WARN] perf_event_open for TID 1 failed: Operation not permitted       
[WARN] perf_event_open for TID 6 failed: Operation not permitted
[...]
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'

*******

nobody@75d275dcf8f7:/home/nobody/async-profiler$ ./profiler.sh 1 --all-user
[ERROR] Perf events unavailable
```

Provisionning:
```
nobody@75d275dcf8f7:/home/nobody/provisioning$ ./provisioning.sh                           
Error: Could not find or load main class org.apache.james.cli.ServerCmd
Caused by: java.lang.ClassNotFoundException: org.apache.james.cli.ServerCmd
Error: Could not find or load main class org.apache.james.cli.ServerCmd
Caused by: java.lang.ClassNotFoundException: org.apache.james.cli.ServerCmd
Error: Could not find or load main class org.apache.james.cli.ServerCmd
Caused by: java.lang.ClassNotFoundException: org.apache.james.cli.ServerCmd
Creating mailbox INBOX
```

Likely because everything belongs to root user. So the user `nobody` can't create folders/files and write in it. Can't seem to find the classpath either.

That makes me think stronger that the JIB community (despite pretending trying to abstract docker best practices) did not really want to bother with it and relegates it to the base image. So I think if we really want to run james as a non root user, there is not much choice than to have our own base image (so that we maintain) where we create a james user, and assign him enough rights in a working space to make this clean.
