### ISSUE TITLE
JMAP endpoint should support being called with accountIds of delegated accounts

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4679]
## Why

https://github.com/linagora/james-project/issues/3949
JMAP endpoints should support being called with accountIds of delegated accounts and needs to proceed with authorization logic according to delegations.

## Require
https://github.com/linagora/james-project/issues/4673

## How
- Find all methods implemented from the `MethodRequiringAccountId` interface (eg: QuotaGetMethod, VacationResponseGetMethod...)
Note that you should ignore the `Delegated/set` with accountId of another owner.

- Using `DelegationStore` to check accountId in request is delegated or not

## Dod

- Add test cases for each related jmap method

**Comment by chibenwa** [comment]
> Note that you should ignore the Delegated/set with accountId of another owner.

Nope, we would have the necessary informations to implement these controls by using the loggedIn user field in mailboxSession IMO

**Comment by chibenwa** [comment]
TODO upload download, etc...

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1374

**Comment by chibenwa** [comment]
Can be split into sub-parts. EG:

 - [ ] Delegation for JMAP API
 - [ ] Delegation for upload
 - [ ] Delegation for dowloads
 - [ ] Delegation for all kind of push
 - ...

**Comment by quantranhong1999** [comment]
Added ` Delegate/set should only be called by primaryAccount` to the above comment so we do not forget it.

**Comment by vttranlina** [comment]
upload + download: PIC  = TUNG

**Comment by chibenwa** [comment]
Remove `Delegation for session route?` and `Delegation for evenSource route` as it is covered by push

**Comment by vttranlina** [comment]
Upload + Download pr: https://github.com/apache/james-project/pull/1382

**Comment by quantranhong1999** [comment]
> Delegation for all kind of push 

This seems not straightforward as others so I think about the direction a bit first.

- Webpush:
  - Webpush is more binding to deviceClient (subscription) than the accountId.
  Therefore, delegated users need to create a new subscription when using the delegated account to receive the notifications (of the delegated account).
  - Upon delegated users still want to receive delegated account's notifications when switching back to their primary accounts, they can keep/remove the subscription.
  - Issues (could be in other tickets):
    - Handle duplicate deviceClientId (on the same device, 1 of Bob for his primary account and 2 of Bob's delegated account)
    - Delegated WebPush subscription should be removed when the delegation is removed

- Websocket:
  - Binding to accountId rather than device
  Delegated users should receive delegated account notifications when opening the WebSocket connection quite straightforward.
  - Delegated users likely can not receive delegated account's notifications when switching back to their primary account.
  (Or open a dedicated WebSocket connection to only receive delegated account notifications?)

- SSE:
  - No binding to accountId for now but rather the logged-in user
  => We may need to create a new query param for accountId. e.g `.../eventSource?accountId=dasdas7`

**Comment by quantranhong1999** [comment]
Another approach for WebPush but comes with diff behavior: 

Say Alice delegates Bob to access her account.
To receive Alice's notifications, Bob will not create a subscription in the name of Alice (as currently PushSubscription only ties to authenticated credentials) but create a subscription in the name of himself. Then when we push Alice notifications (use `PushListener`), we check `DelegationStore` and push for Bob also.

The pros of this approach is easy to do, but the cons is that Bob can be flooded with Alice's notification even when he switches back to his primary account (the client-side can choose not to display Alice's notification in that case anyway).

The way we implement the delegation for pushes may depend on the behavior we want first.
WDYT?

**Comment by chibenwa** [comment]
GIVEN Alice delegates her account to BOB then BOB receives notifications for BOB AND ALICE

**Comment by quantranhong1999** [comment]
pushes: https://github.com/apache/james-project/pull/1386
