### ISSUE TITLE
RabbitMQMailQueue: clean up cassandra projection when we can't publish to Rabbit.

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4796]
When we cannot publish to rabbit, we end up with a dandling entry within the projection.

In a best effort move to clean up things if the message can't be published manage the error by removing it from the projection.

**Comment by vttranlina** [comment]
> dequeueShouldWorkAfterNetworkOutage => do not crash when fail loading the content: nack and put it in "dead letter" ;-)

The current source code already handles it, it does not crash. 
The test fails because of incorrect code in test

> enqueuedEmailsShouldNotBeLostDuringRabbitMQOutages
> 1. publish the mail
> 2. clear the rabbitMQ mail queue manually
> 3. republish
> 4. and then ensure we can dequeue the mail

I'm confused, "3. republish" your mean is `getMailQueue().republishNotProcessedMails(` ? How we can republish when the mail queue is empty? If your mean is a "re-enqueue" mail, hence it confuse with the test name "enqueued email should not be lost during rabbitmq outages"

I have a fixup commit for test, but not sure it is the correct expected: https://github.com/apache/james-project/commit/edfe55278ed49b8fcabcd7de0f4c4b4d2591b56a

**Comment by chibenwa** [comment]
> I'm confused, "3. republish" your mean is getMailQueue().republishNotProcessedMails( ? How we can republish when the mail queue is empty? If your mean is a "re-enqueue" mail, hence it confuse with the test name "enqueued email should not be lost during rabbitmq outages"

This "feature allows re-creating the mail queue view from the Cassandra Query View. IE: you can loose RabbitMQ, no problem.

**Comment by chibenwa** [comment]
> I have a fixup commit for test, but not sure it is the correct expected: https://github.com/apache/james-project/commit/edfe55278ed49b8fcabcd7de0f4c4b4d2591b56a

Please always post a branch. I can't cherry pick individual commits @vttranlina

**Comment by vttranlina** [comment]
> Please always post a branch. I can't cherry pick individual commits @vttranlina

https://github.com/vttranlina/james-project/tree/JAMES-3919
