### ISSUE TITLE
Investigate mail.ru mobile app compatibility

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4941]
Connect a mail.ru app to a local IMAP server configured to output client commands

(modify `NettyImapRequestLineReader::nextChar` to do so)

Document commands being used.

Also, configure mail.ru with your linagora mail account and ensure that this works well. 

A user reported email synchronisation to be stucked with mail.ru.

**Comment by vttranlina** [comment]
I tried to use `mail.ru` app on iOS
> A user reported email synchronisation to be stucked with mail.ru.

On my site, some emails sync successfully (2021 -> 6/2023), but it gets stuck when reaching emails dated "06-2023". The "mail counter" still updates later.
Note: The Mail.ru syncs emails in descending order by date and cannot be configured to sync in ascending order.

No production error [log](https://grafana.lin-saas.com/explore?schemaVersion=1&panes=%7B%229z1%22:%7B%22datasource%22:%22logs-saas-lng-prod%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%22james%5C%22,%20container_name%3D%5C%22tmail-backend%5C%22%7D%20%7C%3D%20%60ERROR%60%20%7C%3D%20%60vttran@linagora.com%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22logs-saas-lng-prod%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) was detected. 

I think the debug on local don't make sense, because `mail.ru` still sync successfuly with small mails.

![IMG_D7A6E724326D-1](https://github.com/user-attachments/assets/d7ff4180-8810-45e3-a5f5-3226e2ef69aa)
