### ISSUE TITLE
Fix flaky test PostgresUploadServiceTest.uploadShouldUpdateCurrentStoredUsageUponCleaningUploadSpace

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5058]
Currently, the test is being disabled because it is unstable.
Dod: investigate and fix the issue.

**Comment by vttranlina** [comment]
The reason is the method `cleanupUploadIfNeed` does not ensure the concurrent. https://github.com/apache/james-project/blob/3a95cbb966449fd9a1973de0bb4cf3576c2cd999/server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadServiceDefaultImpl.java#L64
I created the pr fixup: https://github.com/apache/james-project/pull/2068
