### ISSUE TITLE
User renaming: do not require old user to exist

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5085]
# Why

Might not be absolutly necessary IMO

Also the temptation is to "just" change the mail parameter of the ldap without recreating a new user (ie fixed uid)

# How

Add a "force" option that bypasses the user existance check...

**Comment by vttranlina** [comment]
Is it a task to change James source code?

I'm confused here, Is it related to `UsernameChangeTaskStep`?
I see we do not support `updateUser` in ReadOnlyLDAPUserDAO

**Comment by Arsnael** [comment]
Note that James has no right to alter data on ldap so far in our code.

I think it is for the user renaming task, to which usually we require that old user and new one exist to do the migration

What I think is @chibenwa saying here, the use case here would be:
- I have a user bob@example.com
- I want to change it to bobette@example.com
- Instead of creating the new user bobette@example.com, run the renaming user task, then delete bob@example.com
- I just change manually bob@example.com to bobette@example.com on the ldap directly (admin operation responsible of LDAP)
- Then I just run the renaming task. bob does not exist in ldap anymore but we should still be able to migrate his stuff from james?

Correct @chibenwa ?

**Comment by vttranlina** [comment]
very clear, thank you @Arsnael

**Comment by vttranlina** [comment]
PR https://github.com/apache/james-project/pull/2054

**Comment by chibenwa** [comment]
> Correct @chibenwa ?

Yes correct
